// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:43fefa92-d15e-4f9b-a42a-7ccbcfbbf801",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jkvmgVJEf",
    "aws_user_pools_web_client_id": "4kq7b2m03f68aqa7jqr4c34toi",
    "oauth": {}
};


export default awsmobile;
