/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:43fefa92-d15e-4f9b-a42a-7ccbcfbbf801",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jkvmgVJEf",
    "aws_user_pools_web_client_id": "4kq7b2m03f68aqa7jqr4c34toi",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://umkwemz75rfqvbcokzz5muehiq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
